### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by zephinax** [BetaLost/PyPass#3]
Hey, I really like your project and i wana to add cool future to it, I send this issue to see is project still alive ✨

**Comment by hsover** [comment]
Sorry its been a long time since I checked this repo. What's up?

**Comment by zephinax** [comment]
> Sorry its been a long time since I checked this repo. What's up?

I try to add sync future to your project but because of my poor knowledge in python i can't do it perfectly, let me explain to you.
My goal is we can sync passwords between our systems but how? If we can fork your repo and make privet repository, then generate github privet key and put privet repo url and priver key in pypass setting, we can pull and push to that repo, so if you can add future that when pypass opening, pull passwords from that repo and when add password, push new database.json to that url, now we can have all passwords between all systems. 
Did you get my idea?

**Comment by hsover** [comment]
I think I understood what you want to implement, but one of the main design points in this project is that the program will never upload anything to anywhere, and will only connect to the internet to get the latest version of the software. What you can do is copy the files between the systems, either online or offline.

Also, I don't think it is a very good idea to use Github as a cloud server to sync passwords, that isn't what it's designed for.

But I will look into this feature to see if there's a good way to implement it.

**Comment by zephinax** [comment]
Thanks for your support, I can't wait for it !
